config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {invitations: 'users/invitations'}, skip: [:registrations]
  devise_scope :user do
    get 'users/sign_up' => 'users#new',                             as: 'user_sign_up'
    get 'users/cancel'  => 'users#cancel',                          as: 'user_cancel'
    get 'users/edit'    => 'devise_invitable/registrations#edit',   as: 'edit_user_registration'
    put 'users'         => 'devise_invitable/registrations#update', as: 'user_registration'
    root to: 'devise/sessions#new'
  end
  resources :users, only: [:index, :show]

  resources :tracks, except: [:new, :edit]

  resources :loci, only: [:update]

  resources :projects_datapaths, only: [:create, :destroy] do
    get 'browser', on: :collection
  end

  resources :share_links, except: [:index, :show]

  resources :projects

  resources :projects_users, only: [:update]

  namespace :stream_services, path: 'stream', module: false do
    resources :track, only: :show, controller: 'stream_services', format: /[^\/]+/
  end

  resources :groups, except: :index

  resources :datapaths, except: :show

  get 'search', to: 'search#search'

  get 'help', to: 'static_pages#help'

  match 'user_root' => 'projects#index', via: [:get]
end

app/models/datapath.rb
class Datapath < ActiveRecord::Base
  has_many :datapaths_users, dependent: :destroy
  has_many :users, through: :datapaths_users, dependent: :destroy

  before_destroy :destroy_associated_tracks
  has_many :projects_datapaths, dependent: :destroy
  has_many :projects, through: :projects_datapaths

  validates_path_of :path, allow_empty: true, allow_file: false
  validates_uniqueness_of :path

  protected

  def destroy_associated_tracks
    Track.includes(:projects_datapath).where(projects_datapaths: {datapath_id: id}).destroy_all
  end
end

app/controllers/datapaths_controller.rb
class DatapathsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @datapath = Datapath.new
  end

  def new
  end

  def edit
  end

  def create
    @datapath = Datapath.new(datapath_params)
    @datapath.save
  end

  def update
    @datapath.update(datapath_params)
  end

  def destroy
    @datapath = Datapath.destroy(params[:id])
  end

  private

  def datapath_params
    params.require(:datapath).permit(:path, user_ids: [])
  end
end

app/views/datapaths/_datapath.html.erb
<li id="datapath-<%= datapath.id %>" class="datapath">
  <div class="transpanel">
    <div class="right">
      <%= link_to "", edit_datapath_path(datapath), id: "edit-datapath-#{datapath.id}", remote: true, class: "edit-icon edit-datapath-link margin-left" %>
      <%= link_to "", datapath, method: :delete, data: {confirm: "WARNING!!!\nThis action cannot be undone. Deleting this datapath will also permenately delete all associated tracks. Are you sure you want to continue?"}, remote: true, class: "trash-icon margin-left", id: "delete-datapath-#{datapath.id}" %>
    </div>
    <h5 id="datapath-path-<%= datapath.id %>"><%= datapath.path %></h5>

    <% if datapath.users.any? %>
      <ul class="datapath-users inline-list" id="datapath-users-<%= datapath.id %>">
        <% datapath.users.each do |user| %>
          <li><span class="label secondary round"><%= user.handle %></span></li>
        <% end %>
      </ul>
    <% else %>
      <span class="no-datapath-users">No managers assigned</span>
    <% end %>
  </div>
</li>

app/views/datapaths/_form.html.erb
<%= form_for @datapath, remote: true do |f| %>
  <% if @datapath.errors.any? %>
    <div class="field">
      <p style="color:#FF3333">Please check the highlighted <%= "error".pluralize(@datapath.errors.count) %> below:</p>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :path %>
    <%= f.text_field :path, placeholder: 'new datapath' %>
  </div>

  <div class="field">
    <%= f.label :users %>
    <%= f.collection_select :user_ids, User.with_role(:manager), :id, :handle_with_email, {}, {multiple:true, title: :email} %>
  </div>

  <div class="actions">
    <%= f.submit class: 'button tiny radius' %>
    <%= link_to "Cancel", "#", class: 'button tiny radius datapath-cancel no-margin-bottom' %>
  </div>
<% end %>

app/views/datapaths/create.js.erb
$('.new_datapath').remove();
<% if @datapath.errors.any? %>
  $('#new-datapath').append('<%= j render("form") %>');
  DatapathUsers.applySelect2();
<% else %>
  $('#datapath-list').append('<%= j render(@datapath) %>');
  $('#new-datapath-link').show();
  <% @datapath = Datapath.new %>
  DatapathUsers.applySelect2();
  $('#no-datapaths').remove();
<% end %>

app/views/datapaths/destroy.js.erb
$('#datapath-<%= @datapath.id %>').remove();
if ($('#datapath-list').find('.datapath').length == 0) {
  $('#datapath-list').append('<li id="no-datapaths">There are currently no datapaths in the system</li>');
}

app/views/datapaths/edit.js.erb
$('#edit-datapath-<%= @datapath.id %>').hide();
$('#datapath-users-<%= @datapath.id %>').hide();
$('#datapath-<%= @datapath.id %> .transpanel').append('<%= j render("form") %>');
DatapathUsers.applySelect2();

app/views/datapaths/index.html.erb
<div class="row">
  <div class="small-12 medium-10 medium-centered columns">
    <h3>Datapaths</h3>
    <div id="new-datapath">
      <%= link_to "Create new datapath", new_datapath_path, id: "new-datapath-link", class: "button tiny radius", remote: true %>
    </div>

    <ul id="datapath-list" class="small-block-grid-1 medium-block-grid-2">
      <% if @datapaths.count > 0 %>
        <%= render @datapaths %>
      <% else %>
        <li id="no-datapaths">
          There are currently no datapaths in the system
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/datapaths/new.js.erb
$('#new-datapath-link').hide();
$('#new-datapath').append('<%= j render("form") %>');
DatapathUsers.applySelect2();

app/views/datapaths/update.js.erb
<% if @datapath.errors.any? %>
  $('form#edit_datapath_<%= @datapath.id %>').remove();
  $('#datapath-<%= @datapath.id %> .transpanel').append('<%= j render("form") %>');
  DatapathUsers.applySelect2();
<% else %>
  $('form#edit_datapath_<%= @datapath.id %>').remove();
  $('#datapath-<%= @datapath.id %>').replaceWith('<%= j render(@datapath) %>' )
<% end %>