config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {invitations: 'users/invitations'}, skip: [:registrations]
  devise_scope :user do
    get 'users/sign_up' => 'users#new',                             as: 'user_sign_up'
    get 'users/cancel'  => 'users#cancel',                          as: 'user_cancel'
    get 'users/edit'    => 'devise_invitable/registrations#edit',   as: 'edit_user_registration'
    put 'users'         => 'devise_invitable/registrations#update', as: 'user_registration'
    root to: 'devise/sessions#new'
  end
  resources :users, only: [:index, :show]

  resources :tracks, except: [:new, :edit]

  resources :loci, only: [:update]

  resources :projects_datapaths, only: [:create, :destroy] do
    get 'browser', on: :collection
  end

  resources :share_links, except: [:index, :show]

  resources :projects

  resources :projects_users, only: [:update]

  namespace :stream_services, path: 'stream', module: false do
    resources :track, only: :show, controller: 'stream_services', format: /[^\/]+/
  end

  resources :groups, except: :index

  resources :datapaths, except: :show

  get 'search', to: 'search#search'

  get 'help', to: 'static_pages#help'

  match 'user_root' => 'projects#index', via: [:get]
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def search
    @q = params[:q]

    @projects_and_tracks = {}
    projects = Project.accessible_by(current_ability).
      search(name_or_tracks_name_or_tracks_path_cont: @q).
      result(distinct: true).order('projects.id ASC')

    users = User.search(email_or_first_name_or_last_name_cont: @q).result
    users_projects = []
    users.each do |user|
      users_projects << user.projects.select{|p| can? :read, p}
    end

    projects = projects | users_projects.flatten.uniq

    projects.each do |project|
      @projects_and_tracks[project] = { users: [], tracks: [] }
      project.users.each do |user|
        @projects_and_tracks[project][:users] << user if matches_term?(user)
      end
    end

    tracks = Track.accessible_by(current_ability).search(name_or_path_cont: @q).result.
      order('tracks.projects_datapath_id ASC')
    tracks.each { |track| @projects_and_tracks[track.project][:tracks] << track }

    @groups_and_users = {}
    groups = Group.accessible_by(current_ability).search(name_cont: @q).result
    users_groups = []
    users.each do |user|
      users_groups << user.groups.select {|group| can? :read, group}
    end
    groups = groups | users_groups.flatten.uniq
    groups.each {|group| @groups_and_users.merge!(group => group.members.select {|member| member if users.include? member})}
  end

  private

  def matches_term?(user)
    [user.email, user.first_name, user.last_name].join('@@').match(/#{@q}/i).present?
  end
end

app/views/search/search.html.erb
<div class="row">
  <div class="small-12 medium-10 medium-centered columns">
    <div class="transpanel" data-query=<%= @q %>>
      <% if @projects_and_tracks.any? || @groups_and_users.any? %>
        <% if @projects_and_tracks.any? %>
          <h3>Projects and Tracks</h3>
          <div class="group-by">
            <ul id="projects-and-tracks" class="by-groups">
              <% @projects_and_tracks.each do |project, hash| %>
                <li class="search-result">
                  <div class="by-group">
                    <i class="by-icon by-open"></i>
                    <%= link_to project.name, project_path(project) %>
                    (owner: <%= project.owner.handle %>)
                    [<%= pluralize(project.tracks.count, 'track') %>]
                  </div>
                  <% if hash[:users].any? %>
                    <ul class="cloud-tag by-items">
                      <% hash[:users].each do |user| %>
                        <li><span><%= user.handle_with_email %></span></li>
                      <% end %>
                    </ul>
                  <% end %>
                  <ul class="tracks by-items">
                    <%= render hash[:tracks] %>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <% if @groups_and_users.any? %>
          <h3>Groups and Users</h3>
          <div class="group-by">
            <ul id="groups-and-users" class="by-groups">
              <% @groups_and_users.each do |group, members_array| %>
                <li class="search-result">
                  <div class="by-group">
                    <i class="by-icon by-open"></i>
                    <%= link_to group.name, group_path(group) %> (owner: <%= group.owner.handle %>) [<%= pluralize(group.members.count, 'user') %>]
                  </div>
                  <ul class="users by-items">
                    <%= render members_array %>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <% else %>
        <p>Your search - <b><%= @q %></b> - did not return any results.</p>
        <p>Suggestions:</p>
        <ul>
          <li>Make sure all words are spelled correctly.</li>
          <li>Try different keywords.</li>
          <li>Try more general keywords.</li>
          <li>Try fewer keywords.</li>
        </ul>
      <% end %>
    </div>
  </div>
</div>