config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {invitations: 'users/invitations'}, skip: [:registrations]
  devise_scope :user do
    get 'users/sign_up' => 'users#new',                             as: 'user_sign_up'
    get 'users/cancel'  => 'users#cancel',                          as: 'user_cancel'
    get 'users/edit'    => 'devise_invitable/registrations#edit',   as: 'edit_user_registration'
    put 'users'         => 'devise_invitable/registrations#update', as: 'user_registration'
    root to: 'devise/sessions#new'
  end
  resources :users, only: [:index, :show]

  resources :tracks, except: [:new, :edit]

  resources :loci, only: [:update]

  resources :projects_datapaths, only: [:create, :destroy] do
    get 'browser', on: :collection
  end

  resources :share_links, except: [:index, :show]

  resources :projects

  resources :projects_users, only: [:update]

  namespace :stream_services, path: 'stream', module: false do
    resources :track, only: :show, controller: 'stream_services', format: /[^\/]+/
  end

  resources :groups, except: :index

  resources :datapaths, except: :show

  get 'search', to: 'search#search'

  get 'help', to: 'static_pages#help'

  match 'user_root' => 'projects#index', via: [:get]
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, class_name: 'User', foreign_key: 'user_id', source: :user, inverse_of: :groups
  belongs_to :owner, class_name: "User", foreign_key: :owner_id

  validates_presence_of :name
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  skip_load_resource only: [:new]

  respond_to :html

  def show
  end

  def new
    @group = Group.new(owner: current_user, members: [current_user])
  end

  def edit
  end

  def create
    @group.owner ||= current_user
    @group.members << @group.owner unless @group.members.include?(@group.owner)
    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if params['group'] && params['group']['member_ids']
      params['group']['member_ids'] << @group.owner.id unless params['group']['member_ids'].include?(@group.owner.id)
    end
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @group.destroy
    redirect_to users_path
  end

  private
  def group_params
    params.require(:group).permit(:name, member_ids: [])
  end
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div class="field">
      <p style="color:#FF3333">Please check the highlighted <%= "error".pluralize(@group.errors.count) %> below:</p>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, size: 60, placeholder: 'Group name' %>
  </div>

  <div id="group-owner">
    Group owner: <%= link_to @group.owner.handle, @group.owner %>
  </div></br>

  <div class="field">
    <%= f.collection_select :member_ids, User.all_except(@group.owner), :id, :handle_with_email, {}, {multiple:true} %>
  </div>

  <div class="actions">
    <%= f.submit class: 'button tiny radius' %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<li id="group_<%= group.id %>">
  <%= link_to group.name, group %>
  <span class="subdue owner-icon icon-key" title="owner"><%= group.owner.handle %></span>
</li>

app/views/groups/edit.html.erb
<div class="row">
  <div class="small-12 medium-10 medium-centered columns">
    <div class="transpanel">
      <h1>Edit group</h1>

      <%= render 'form' %>

      <%= link_to 'Cancel', users_path, class: 'button tiny radius' %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="row">
  <div class="small-12 medium-10 medium-centered columns">
    <div class="transpanel">
      <h1>New group</h1>

      <%= render 'form' %>

      <%= link_to 'Cancel', users_path, class: 'button tiny radius' %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="row">
  <div class="small-12 medium-10 medium-centered columns">
    <div class="transpanel">
      <div class="clearfix">
        <h3 class="left"><%= @group.name %></h3>
        <%= render partial: 'timestamps', locals: { record: @group } %>
      </div>

      <ul class="no-bullet" id="members">
        <%= render @group.members %>
      </ul>
    </div>

    <% if can? :manage, @group %>
      <%= link_to 'Edit', edit_group_path(@group), class: 'button tiny radius' %>
      <%= link_to 'Back', :back, class: 'button tiny radius' %>
      <%= link_to 'Delete', @group, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button tiny radius [secondary alert success] right' %>
    <% else %>
      <%= link_to 'Back', :back, class: 'button tiny radius' %>
    <% end %>
  </div>
</div>