config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {invitations: 'users/invitations'}, skip: [:registrations]
  devise_scope :user do
    get 'users/sign_up' => 'users#new',                             as: 'user_sign_up'
    get 'users/cancel'  => 'users#cancel',                          as: 'user_cancel'
    get 'users/edit'    => 'devise_invitable/registrations#edit',   as: 'edit_user_registration'
    put 'users'         => 'devise_invitable/registrations#update', as: 'user_registration'
    root to: 'devise/sessions#new'
  end
  resources :users, only: [:index, :show]

  resources :tracks, except: [:new, :edit]

  resources :loci, only: [:update]

  resources :projects_datapaths, only: [:create, :destroy] do
    get 'browser', on: :collection
  end

  resources :share_links, except: [:index, :show]

  resources :projects

  resources :projects_users, only: [:update]

  namespace :stream_services, path: 'stream', module: false do
    resources :track, only: :show, controller: 'stream_services', format: /[^\/]+/
  end

  resources :groups, except: :index

  resources :datapaths, except: :show

  get 'search', to: 'search#search'

  get 'help', to: 'static_pages#help'

  match 'user_root' => 'projects#index', via: [:get]
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :projects_users, dependent: :destroy
  has_many :users, through: :projects_users

  has_many :projects_datapaths, dependent: :destroy
  has_many :datapaths, through: :projects_datapaths
  has_many :tracks,    through: :projects_datapaths, source: :tracks

  belongs_to :owner, class_name: "User", foreign_key: :owner_id

  validates_presence_of :name, :owner_id

  def allowed_paths
    projects_datapaths.collect{ |project_datapath| project_datapath.full_path }
  end

  def regular_users
    users.where(projects_users: { read_only: false })
  end

  def read_only_users
    users.where(projects_users: { read_only: true })
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  respond_to :html, only: [:index, :show]
  respond_to :js, :json, only: [:new, :create, :edit, :update, :index]

  include LocusService

  def index
    @filter = params[:filter]
    @projects = Project.accessible_by(current_ability).
      search(name_or_description_or_owner_email_or_owner_first_name_or_owner_last_name_cont: @filter).
      result(distinct: true).order('projects.id ASC')
  end

  def show
    @project = Project.includes(:projects_users, :users).find(params[:id])
    @locus = locus_for(current_user, @project)
  end

  def new
    @project = Project.new(owner: current_user)
  end

  def edit
  end

  def create
    @project.save
  end

  def update
    # TODO: move to projects_users controller? And keep here only basic project changes (ie: name)
    # TODO: blank users should give an error?
    if params['project']['user_ids']
      params['project']['user_ids'] = [] if params['project']['user_ids'].blank?
    end

    respond_to do |format|
      @project.update(update_params)
      format.js
      format.json { respond_with_bip(@project) }
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url
  end

  private

  def create_params
    params.require(:project).permit(:name, :description).merge(owner_id: current_user.id)
  end

  def update_params
    params.require(:project).permit(:name, :description, user_ids: [])
  end
end

app/views/projects/_form.html.erb
<%= form_for @project, remote: true do |f| %>
  <% if @project.errors.any? %>
    <div class="field">
      <p style="color:#FF3333">Please check the highlighted <%= "error".pluralize(@project.errors.count) %> below:</p>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit class: 'button tiny radius', id: "create-project" %>
    <%= link_to 'Cancel', '#', class: 'button tiny radius', id:'project-cancel' %>
  </div>

  <div class="field">
    <%= f.text_field :name, size: 60, placeholder: 'Name' %>
  </div>
  <div class="field">
    <%= f.text_area :description, size: "60x3", placeholder: 'Description' %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<li id="project_<%= project.id %>">
  <ul class="no-bullet transpanel project-tile">
    <li class="headline">
      <%= link_to project.name, project, class: "text-panel-overhang" %>
    </li>
    <li>
      <ul class="keys-inline-list">
        <li class="track-icon icon-key" title="tracks"><%= project.tracks.count %></li>
        <li class="users-icon icon-key" title="users"><%= project.users.count %></li>
      </ul>
    </li>
    <li class="sub-text text-panel-overhang owner-icon icon-key" title="owner">
      <% if can? :show, project.owner %>
        <%= link_to project.owner.handle, project.owner, class: "text-panel-overhang" %>
      <% else %>
        <%= project.owner.handle %>
      <% end %>
    </li>
    <li class="sub-text updated-at-icon icon-key" title="updated_at"><%= local_time_ago(project.updated_at) %></li>
  </ul>
</li>

app/views/projects/_project_track.html.erb
<li class="project-track" id="project-track-<%= track.id %>" data-stream-url=<%= stream_services_track_path(track) %> data-track-name=<%= track.name %>>
  <%= link_to track.name, "#" %>
</li>

app/views/projects/_project_user.html.erb
<div class="user-list-item" id="user-<%= user.id %>">
  <% if can? :manage, @project %>
    <div class="clearfix">
      <%= link_to user do %>
        <%= image_tag avatar_url(user), class: "avatar" %>
        <%= user.handle %>
        <%= render partial: "projects_users/form", locals: { projects_user: @project.projects_users.select {|p_u| p_u.user_id == user.id} } %>
      <% end %>
    </div>
  <% elsif can? :show, user %>
    <%= link_to user do %>
      <%= image_tag avatar_url(user) %>
      <%= user.handle %>
    <% end %>
  <% else %>
    <%= image_tag avatar_url(user) %>
    <%= user.handle %>
  <% end %>
</div>

app/views/projects/_users_form.html.erb
<%= form_for @project, remote: true do |f| %>
  <div class="row">
    <div class="small-12 medium-10 columns">
      <h4>Edit Project Users</h4>
      <div class="field">
        <%= f.collection_select :user_ids, User.all_except(@project.owner), :id, :handle_with_email, {}, {multiple:true, title: :email} %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: 'button tiny radius update-project-users' %>
    <%= link_to 'Cancel', "#", class: 'button tiny radius', id: 'cancel-edit-users' %>
  </div>
<% end %>

app/views/projects/create.js.erb
<% if @project.errors.any? %>
  $('.new_project').remove();
  $('#create-new-project').append('<%= j render("form") %>');
<% else %>
  window.location = '<%= project_path(@project) %>'
  <% flash[:notice] = 'Project was successfully created.'%>
<% end %>

app/views/projects/edit.js.erb
$('#project-users').hide().after('<%= j render("users_form") %>');
$("#project_user_ids").select2({
  placeholder: "Add a user"
});

if (hopscotch.getState() === "tour-project-show-manager:6") {
  hopscotch.startTour(eval($('div[data-tour]').data('tour')), 6);
}

app/views/projects/index.html.erb
<% if current_user.has_role? :manager %>
  <%= render partial: "tour_link", locals: {tour_name: "tour_project_index_manager"} %>
<% else %>
  <%= render partial: "tour_link", locals: {tour_name: "tour_project_index"} %>
<% end %>

<div class="row">
  <div class="small-12 medium-10 columns">
    <div id="create-new-project"></div>

    <div class="row">
      <div class="small-12 medium-6 columns">
        <% if can? :manage, Project %>
          <%= link_to 'New Project', new_project_path, class: "button tiny radius", id: "new-project", remote: true %>
        <% end %>
      </div>

      <div class="small-12 medium-6 columns">
        <% unless @projects.empty? %>
          <%= form_tag(projects_path, method: :get, remote: true) do %>
            <div class="row collapse">
              <div class="small-8 columns">
                <%= text_field_tag :filter, nil , placeholder: "Filter projects", value: @filter %>
              </div>
              <div class="small-2 columns">
                <%= submit_tag 'Filter', class: "button postfix postfix-edge" %>
              </div>
              <div class="small-2 columns">
                <%= link_to 'Clear', projects_path, class: "button postfix clear-filter", remote: true %>
              </div>
            </div>
          <% end %>
        <% end %>

      </div>
    </div>

    <ul class="small-block-grid-1 medium-block-grid-3" id="project-list">
      <%= render @projects %>
    </ul>

    <% if @projects.empty? %>
      <div class="transpanel">
        <h3>Projects</h3>
        <% if current_user.invited_by %>
          <p>Please contact <%= mail_to current_user.invited_by.email %> to be added to a project</p>
        <% else %>
          <p>Please contact your admin to be added to a project</p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/index.js.erb
<% if @projects.count > 0 %>
  $('#project-list').html('<%= j render(@projects) %>').highlight('<%= @filter %>');
<% else %>
  $('#project-list').html('<li>No projects found.</li>');
<% end %>

app/views/projects/new.html.erb
<%= render partial: "tour_link", locals: {tour_name: "tour_project_new"} %>

<div class="row">
  <div class="small-12 medium-10 medium-centered columns">
    <div class="transpanel">
      <h1 id="new-project-headline">New project</h1>

      <%= render 'form' %>

      <%= link_to 'Cancel', projects_path, class: 'button tiny radius' %>
    </div>
  </div>
</div>

app/views/projects/new.js.erb
$('#new-project').hide()
$('#create-new-project').html('<%= j render("form") %>');

if (hopscotch.getState() === "tour-project-index-manager:3") {
  hopscotch.startTour(eval($('div[data-tour]').data('tour')), 3);
}

app/views/projects/show.html.erb
<% if can? :manage, @project %>
  <%= render partial: "tour_link", locals: {tour_name: "tour_project_show_manager"} %>
<% else %>
  <%= render partial: "tour_link", locals: {tour_name: "tour_project_show"} %>
<% end %>

<div class="row">
  <div class="small-12 medium-10 medium-centered columns">
    <div class="transpanel">

      <div class="row">
        <div class="small-12 medium-8 columns">
          <h3 id="project-name">
            <%= best_in_place_if can?(:manage, @project), @project, :name,
              {ok_button: 'save', cancel_button: 'cancel'} %>
            <small>
              (owner: <%= @project.owner.handle %>)
            </small>
          </h3>
        </div>
        <div class="small-12 medium-4 columns">
          <%= render partial: 'timestamps', locals: { record: @project } %>
        </div>
      </div>

      <div class="row">
        <div class="small-12 medium-8 columns">
          <p class="project-description">
            <%= best_in_place_if can?(:manage, @project), @project, :description,
              {as: :textarea, ok_button: 'save', cancel_button: 'cancel', place_holder: 'Click to add description'} %>
          </p>
        </div>
      </div>

      <div class="row">
        <div class="small-12 columns">

          <ul class="project-tabs" data-tab>
            <li class="tab-title active"><a id="files-tab" href="#panel1">Files</a></li>
            <li class="tab-title"><a id="users-tab" href="#panel2">Users</a></li>
            <li class="tab-title"><a id="igv-tab" href="#panel3">IGV</a></li>
          </ul>

          <div class="tabs-content project-show-content">
            <div class="content project-datapaths active" id="panel1">
              <h4 class="no-margin-bottom">
                <% if can? :manage, @project %>
                  <span class="datapath-icon icon-key">Datapaths</span>
                  <small>and</small>
                <% end %>
                <span class="track-icon icon-key">Tracks</span>
                <span class="track-count">[<%= @project.tracks.count %>]</span>
                <small>view all your <%= link_to 'tracks', tracks_path, id: "all-user-tracks" %></small>
              </h4>

              <div class="subhead-note">
                <% if can? :manage, @project %>
                  Contact site <%= mail_to ENV['ADMIN_EMAIL'], 'administrator' %> to add/remove datapaths from the project.
                <% else %>
                  Contact <%= mail_to @project.owner.email, 'project owner' %> to add/remove datapaths from the project.
                <% end %>
              </div>

              <table id="track-tree" data-project=<%= @project.id %>>
                <colgroup>
                  <col width="30px"></col>
                  <col width="*"></col>
                  <col width="*"></col>
                  <col width="*"></col>
                  <col width="*"></col>
                </colgroup>
                <thead>
                  <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                </tbody>
              </table>
            </div>

            <div class="content project-attributes" id="panel2">
              <div id="project-users">
                <h4 id="regular-users">
                  <span class="users-icon icon-key">Users [<%= @project.regular_users.count %>]</span>
                  <% if can? :manage, @project %>
                    <small><%= link_to 'Edit Project Users', edit_project_path(@project), id: 'edit-users', remote: true  %></small>
                  <% end %>
                </h4>
                <div id="project-users-regular">
                  <%= render partial: "projects/project_user", collection: @project.regular_users, as: :user %>
                </div>
                <h4 id="read-only-users">
                  <span class="users-icon icon-key">Read-Only Users [<%= @project.read_only_users.count %>]</span>
                </h4>
                <div id="project-users-read-only">
                  <%= render partial: "projects/project_user", collection: @project.read_only_users, as: :user %>
                </div>
              </div>
            </div>

            <div class="content project-js-igv" id="panel3">
              <h6>
                Please select genome to launch embedded igv viewer
              </h6>
              <ul class="inline-list">
                <li><a href="#" class="igv-js-link" data-project-genome='hg18'>hg18</a></li>
                <li><a href="#" class="igv-js-link" data-project-genome='hg19'>hg19</a></li>
              </ul>

              <div class="project-tracks">
                <h6>
                  Click <span class="track-icon icon-key">tracks</span> below to load them into igv viewer
                </h6>
                <div class="subhead-note">
                  Only tracks with 'bam' extension are available to view in the igv javascript viewer
                </div>
                <ul class="track-cloud">
                  <% @project.tracks.select{|track| track.file_format == 'bam'}.each do |track| %>
                    <%= render partial: "project_track", locals: {track: track} %>
                  <% end %>
                </ul>
                <hr>
              </div>

              <div class="igv-js" data-locus-path=<%= locus_path(@locus) %> data-locus-range=<%= @locus.range %>>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="small-12 medium-10 medium-centered columns">
    <%= link_to 'Back', :back, class: 'button tiny radius' %>
    <% if can? :manage, @project %>
      <%= link_to 'Delete', @project, method: :delete, data: { confirm: 'Are you sure? Clicking this button will delete this project and all its associated tracks' }, class: 'button tiny radius [secondary alert success] right', id: "delete-project" %>
    <% end %>
  </div>
</div>

app/views/projects/update.js.erb
$('#edit_project_<%= @project.id %>').remove();
<% if @project.errors.any? %>
  $('#project-users').append('<%= j render("users_form") %>');
<% else %>
  $('#project-users').show();
  $('#project-users-regular').html("<%= escape_javascript(render partial: 'projects/project_user', collection: @project.regular_users, as: :user) %>");
  $('#project-users-read-only').html("<%= escape_javascript(render partial: 'projects/project_user', collection: @project.read_only_users, as: :user) %>");
  $('.edit_projects_user').submitOnCheck()
<% end %>